backend:
  name: github
  repo: jwknz/gatsby-ncms-pg
  publish_mode: editorial_workflow

media_folder: static/media

collections:

  - name: main
    label: Main Pages
    folder: static/pages
    filter: {field: "section", value: "main"}
    create: true
    delete: true
    section: main
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: notices
    label: Notices
    folder: static/pages
    filter: {field: "section", value: "notices"}
    create: true
    delete: true
    section: notices
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }