backend:
  name: github
  repo: jwknz/gatsby-ncms-pg
  publish_mode: editorial_workflow

media_folder: static/media

collections:
  - name: "business"
    label: "Business Blog"
    folder: "_posts/business/"
    create: true
    delete: true
    filter:
      - field: "categories"
        value: "business"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"

      - label: "Author"
        name: "author"
        widget: "string"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Date"
        name: "date"
        widget: "datetime"

      - label: "Category"
        name: "categories"
        widget: "select"
        options: 
          - label: "Business"
            value: "business"

      - label: "Description"
        name: "description"
        widget: "text"

      - label: "Image"
        name: "image"
        widget: "string"

      - label: "Body"
        name: "body"
        widget: "markdown"