backend:
  name: github
  repo: jwknz/gatsby-ncms-pg
  publish_mode: editorial_workflow

media_folder: static/media

collections:

  - name: new
    label: New Page or Notice
    folder: static/drafts
    create: true
    delete: true
    fields:
      - { name: path, label: Path }
      - { label: Section, name: section, widget: list, options: ["main", "notices"], default: ["notices"], allow_add: false}
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: main
    label: Main Pages
    folder: static/pages
    filter: {field: "section", value: "main"}
    section: main
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: notices
    label: Notices
    folder: static/pages
    filter: {field: "section", value: "notices"}
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }